version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=next_auth_prisma_db
    volumes:
      - react-clone:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  react-clone:
